[project]
name = "blog"
version = "1.0.0"
description = "Kyle Stanfield's personal site and blog."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"